environment:
  matrix:
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -m pip install -U pip setuptools
  - pip install -e .
  - pip install securesystemslib[crypto,pynacl] python-dateutil
  - if %PYTHON_VERSION%==2.7 pip install mock

build: false

test_script:
  - cd tests
  - python aggregate_tests.py
