CommonModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  EXPORTS ALL;

  RoleType        ::= ENUMERATED {root, targets, snapshot, timestamp}

  -- String types.
  Filename        ::= VisibleString (SIZE(1..32))
  -- No known path separator allowed in a strict filename.
  StrictFilename  ::= VisibleString (SIZE(1..32))
                                    (PATTERN "[^/\\]+")
  BitString       ::= BIT STRING    (SIZE(1..1024))
  OctetString     ::= OCTET STRING  (SIZE(1..1024))
  HexString       ::= VisibleString (SIZE(1..1024))
                                    (PATTERN "[0-9a-f]+")
  -- Table 1 of RFC 4648.
  Base64String    ::= VisibleString (SIZE(1..1024))
                                    (PATTERN "[A-Za-z0-9\+/=]+")
  -- Adjust length of SEQUENCE OF to your needs.
  Paths           ::= SEQUENCE (SIZE(1..8)) OF Path
  Path            ::= VisibleString (SIZE(1..32))
                                    (PATTERN "[\w\*\\/]+")
  -- Adjust length of SEQUENCE OF to your needs.
  URLs            ::= SEQUENCE (SIZE(1..8)) OF URL
  URL             ::= VisibleString (SIZE(1..1024))
  -- A generic identifier for vehicles, primaries, secondaries.
  Identifier      ::= VisibleString (SIZE(1..32))

  Natural         ::= INTEGER (0..MAX)
  Positive        ::= INTEGER (1..MAX)
  Length          ::= Positive
  Threshold       ::= Positive
  Version         ::= Positive
  -- The date and time in UTC encoded as a UNIX timestamp.
  UTCDateTime     ::= Positive

  BinaryData      ::= CHOICE {
    bitString     BitString,
    octetString   OctetString,
    hexString     HexString,
    base64String  Base64String
  }

  -- Adjust length of SEQUENCE OF to your needs.
  Hashes          ::= SEQUENCE (SIZE(1..8)) OF Hash
  Hash            ::= SEQUENCE {
    function      HashFunction,
    digest        BinaryData
  }
  HashFunction ::= ENUMERATED {sha224, sha256, sha384, sha512, sha512-224,
                               sha512-256, ...}

  -- Adjust length of SEQUENCE OF to your needs.
  Keyids          ::= SEQUENCE (SIZE(1..8)) OF Keyid
  -- Usually, a hash of a public key.
  Keyid           ::= HexString

  -- Adjust length of SEQUENCE OF to your needs.
  Signatures      ::= SEQUENCE (SIZE(1..8)) OF Signature
  Signature       ::= SEQUENCE {
    keyid         Keyid,
    method        SignatureMethod,
    -- For efficient checking, sign the hash of the message instead of the
    -- message itself.
    hash          Hash,
    -- The signature itself.
    value         HexString
  }
  SignatureMethod ::= ENUMERATED {rsassa-pss, ed25519, ...}

  -- Adjust length of SEQUENCE OF to your needs.
  PublicKeys      ::= SEQUENCE (SIZE(1..8)) OF PublicKey
  PublicKey       ::= SEQUENCE {
    publicKeyid     Keyid,
    publicKeyType   PublicKeyType,
    publicKeyValue  BinaryData
  }
  PublicKeyType   ::= ENUMERATED {rsa, ed25519, ...}

  -- "Arrays" with lengths.
  SequenceOfPaths ::= SEQUENCE {
    length  Length,
    paths   Paths
  }
  SequenceOfURLs ::= SEQUENCE {
    length  Length,
    urls    URLs
  }
  SequenceOfHashes ::= SEQUENCE {
    length  Length,
    hashes  Hashes
  }
  SequenceOfKeyids ::= SEQUENCE {
    length  Length,
    keyids  Keyids
  }
  SequenceOfSignatures ::= SEQUENCE {
    length      Length,
    signatures  Signatures
  }
  SequenceOfPublicKeys ::= SEQUENCE {
    length      Length,
    publicKeys  PublicKeys
  }

END
