MetadataModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  IMPORTS Positive, RoleType, Signatures, UTCDateTime FROM CommonModule;
  IMPORTS RootMetadata                                FROM RootModule;
  IMPORTS TargetsMetadata                             FROM TargetsModule;
  IMPORTS SnapshotMetadata                            FROM SnapshotModule;
  IMPORTS TimestampMetadata                           FROM TimestampModule;

  Metadata      ::= SEQUENCE {
    signed      Signed,
    signatures  Signatures
  }
  Signed        ::= SEQUENCE {
    type        RoleType,
    expires     UTCDateTime,
    version     Positive,
    body        CHOICE {RootMetadata, TargetsMetadata,
                        SnapshotMetadata, TimestampMetadata}
  }

END
