MetadataModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  IMPORTS Positive, RoleType, Signatures  FROM CommonModule;
  IMPORTS RootMetadata                    FROM RootModule;
  IMPORTS TargetsMetadata                 FROM TargetsModule;
  IMPORTS SnapshotMetadata                FROM SnapshotModule;
  IMPORTS TimestampMetadata               FROM TimestampModule;

  -- UTC date and time in the ISO 8601 format ("YYYY-MM-DDTHH:MM:SSZ").
  UTCDateTime   ::= VisibleString (PATTERN "\d(4)-\d(2)-\d(2)T\d(2):\d(2):\d(2)Z")

  Metadata      ::= SEQUENCE {
    signed      Signed,
    signatures  Signatures
  }
  Signed        ::= SEQUENCE {
    type        RoleType,
    expires     UTCDateTime,
    version     Positive,
    body        CHOICE {RootMetadata, TargetsMetadata,
                        SnapshotMetadata, TimestampMetadata}
  }

END
