RootModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  EXPORTS RootMetadata;

  IMPORTS Keyids, PublicKeys, RoleType, Threshold FROM CommonModule;

  RootMetadata ::= SEQUENCE {
    keys        PublicKeys,
    roles       Roles,
    -- https://tools.ietf.org/html/rfc6025#section-2.4.2
    ...
  }
  Roles ::= SEQUENCE {

    role      RoleType,
    -- TAP 5: The URL pointing to the metadata file for this role.
    url       VisibleString,
    keyids    Keyids,
    threshold Threshold,
    ...
  }

END
