SnapshotModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  EXPORTS SnapshotMetadata;

  IMPORTS StrictFilename, Version FROM CommonModule;

  -- Adjust length of SEQUENCE OF to your needs.
  SnapshotMetadata ::= SEQUENCE (SIZE(1..128)) OF FilenameAndVersion
  FilenameAndVersion ::= SEQUENCE {
    filename  StrictFilename,
    version   Version,
    -- https://tools.ietf.org/html/rfc6025#section-2.4.2
    ...
  }

END
