TargetsModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  EXPORTS TargetsMetadata, Target;

  IMPORTS BinaryData,
          Filename,
          Hashes,
          Identifier,
          Keyids,
          Length,
          Natural,
          Paths,
          PublicKeys,
          StrictFilename,
          Threshold FROM CommonModule;

  TargetsMetadata ::= SEQUENCE {
    -- Allowed to have no targets at all.
    numberOfTargets Natural,
    -- Metadata about unencrypted images on a repository.
    targets         Targets,
    -- Delegations are optional.
    delegations     TargetsDelegations OPTIONAL,
    -- https://tools.ietf.org/html/rfc6025#section-2.4.2
    ...
  }

  -- Adjust length of SEQUENCE OF to your needs.
  Targets           ::= SEQUENCE (SIZE(1..128)) OF TargetAndCustom
  TargetAndCustom   ::= SEQUENCE {
    -- The filename, length, and hashes of unencrypted images on a repository.
    target  Target,
    -- This optional attribute is used by the director repository to specify
    -- additional information, such as which images should be installed by
    -- which ECUs, and metadata about encrypted images.
    custom  Custom OPTIONAL
  }
  Target ::= SEQUENCE {
    filename        Filename,
    length          Length,
    numberOfHashes  Length,
    hashes          Hashes
  }
  Custom ::= SEQUENCE {
    -- Information, e.g., serial numbers, that ECUs may use to identify metadata
    -- intended by the director for them.
    ecuIdentifier         Identifier,
    -- Optional attribute: use only if director encrypts images for this ECU
    -- these encrypted images are on the director repository.
    encryptedTarget       Target OPTIONAL,
    -- Optional attribute: use only if ECU keys are asymmetric, and director
    -- uses symmetric keys to encrypt the image decryption key.
    encryptedSymmetricKey EncryptedSymmetricKey OPTIONAL,
    ...
  }
  EncryptedSymmetricKey ::= SEQUENCE {
    -- This is the symmetric key type.
    encryptedSymmetricKeyType   EncryptedSymmetricKeyType,
    -- This is the symmetric key encrypted using the asymmetric ECU key.
    encryptedSymmetricKeyValue  BinaryData
  }
  EncryptedSymmetricKeyType ::= ENUMERATED {aes128, aes192, aes256, ...}

  -- https://github.com/theupdateframework/taps/blob/master/tap3.md
  TargetsDelegations  ::= SEQUENCE {
    -- The public keys of all delegatees.
    numberOfKeys                    Length,
    keys                            PublicKeys,
    -- The role name, filename, public keys, and threshold of a delegatee.
    numberOfRoles                   Length,
    roles                           DelegatedTargetsRoles,
    -- A list of paths to roles, listed in order of priority.
    numberOfPrioritizedPathsToRoles Length,
    prioritizedPathsToRoles         PrioritizedPathsToRoles
  }

  -- Adjust length of SEQUENCE OF to your needs.
  DelegatedTargetsRoles ::= SEQUENCE (SIZE(1..8)) OF DelegatedTargetsRole
  DelegatedTargetsRole  ::= SEQUENCE {
    -- The rolename (e.g., "supplierA-dev").
    rolename        RoleName,
    -- An explicit filename for the role (e.g., "supplierA.ext").
    -- Otherwise, it is implicitly assumed to be ROLENAME.EXT (e.g.,
    -- "supplierA-dev.ext").
    -- Different rolenames MAY use the same filename.
    filename        StrictFilename OPTIONAL,
    -- The public keys used by this role.
    numberOfKeyids  Length,
    keyids          Keyids,
    -- The threshold number of these keys.
    threshold       Threshold
  }
  -- Adjust length of SEQUENCE OF to your needs.
  RoleNames               ::= SEQUENCE (SIZE(1..8)) OF RoleName
  -- No known path separator allowed in a rolename.
  RoleName                ::= StrictFilename
  -- Adjust length of SEQUENCE OF to your needs.
  PrioritizedPathsToRoles ::= SEQUENCE (SIZE(1..8)) OF PathsToRoles
  PathsToRoles            ::= SEQUENCE {
    -- A list of image/target paths entrusted to these roles.
    numberOfPaths Length,
    paths         Paths,
    -- A list of roles required to sign the same metadata about the matching
    -- targets/images.
    numberOfRoles Length,
    roles         RoleNames,
    -- Whether or not this delegation is terminating.
    terminating BOOLEAN DEFAULT FALSE
  }

END
