TimestampModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  EXPORTS TimestampMetadata;

  IMPORTS Filename, Version FROM CommonModule;

  TimestampMetadata ::= SEQUENCE {
    filename  Filename,
    version   Version,
    -- https://tools.ietf.org/html/rfc6025#section-2.4.2
    ...
  }

END
