TimeServerModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  IMPORTS Length,
          Signatures,
          UTCDateTime FROM CommonModule;

  -- What a primary sends the time server: a nonce from each of its secondaries.
  SequenceOfNonces ::= SEQUENCE {
    numberOfNonces  Length,
    nonces          Nonces
  }
  -- Adjust length of SEQUENCE OF to your needs.
  Nonces  ::= SEQUENCE (SIZE(1..128)) OF Nonce
  Nonce   ::= INTEGER

  -- What the time server sends in response.
  SequenceOfCurrentTimes ::= SEQUENCE {
    numberOfCurrentTimes  Length,
    currentTimes          CurrentTimes
  }
  -- Adjust length of SEQUENCE OF to your needs.
  CurrentTimes  ::= SEQUENCE (SIZE(1..128)) OF CurrentTime
  CurrentTime   ::= SEQUENCE {
    signed              NonceAndTimestamp,
    numberOfSignatures  Length,
    signatures          Signatures
  }
  NonceAndTimestamp ::= SEQUENCE {
    nonce     Nonce,
    timestamp UTCDateTime,
    -- https://tools.ietf.org/html/rfc6025#section-2.4.2
    ...
  }

END
