TrustPinningModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN

  IMPORTS Paths, StrictFilename, URLs FROM CommonModule;

  -- https://github.com/theupdateframework/taps/blob/master/tap4.md
  TrustPinning ::= SEQUENCE {
    -- A list of repositories.
    repositories Repositories,
    --A list of multi-repository delegations.
    delegations RepositoryDelegations
  }

  Repositories    ::= SEQUENCE OF Repository
  Repository      ::= SEQUENCE {
    -- A shorthand name for the repository.
    name              RepositoryName,
    -- The base URL to the repository.
    mirrors           URLs,
    -- The name of the directory on the client which contains previous and
    -- current metadata.
    metadataDirectory StrictFilename
  }
  RepositoryNames ::= SEQUENCE OF RepositoryName
  RepositoryName  ::= StrictFilename

  RepositoryDelegations ::= SEQUENCE OF RepositoryDelegation
  RepositoryDelegation  ::= SEQUENCE {
    -- The list of targets delegated to the following repositories.
    paths         Paths,
    -- The repositories which MUST all sign the preceeding targets.
    repositories  RepositoryNames,
    -- Whether or not this delegation is terminating.
    terminating   BOOLEAN DEFAULT FALSE
  }

END
