on:
  workflow_call:
  # Permissions inherited from caller workflow

permissions: {}

jobs:
  sslib-main:
    name: Test securesystemslib main branch (not a merge blocker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TUF
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            requirements/*.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python3 -m pip install --constraint requirements/build.txt tox

      - name: Run tox
        run: tox -e with-sslib-main
