on:
  workflow_call:
  # Permissions inherited from caller workflow

permissions: {}

jobs:
  sslib-main:
    name: Test securesystemslib main branch (not a merge blocker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TUF
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            requirements/*.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python3 -m pip install --constraint requirements/build.txt tox

      - name: Run tox
        run: tox -e with-sslib-main
