on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 3'

permissions:
  contents: read

name: Conformance
jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout conformance client
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run test suite
        uses: theupdateframework/tuf-conformance@500c525c9ce287a472fd334fe8d885cace667d32 # v2.4.0
        with:
          entrypoint: ".github/scripts/conformance-client.py"
